### ISSUE TITLE
Manufacturing Specs of LED PCB

### ISSUE THREAD

**Issue by abtabrizi** [linchangyi1/9DTact#2]
Hi @linchangyi1, thank you for open-sourcing your sensor. 
Can you kindly upload the JLCPCB manufacturing specifications used for the LED PCB?

The specs I am interested in are:
![image](https://github.com/user-attachments/assets/0664fe65-034f-4305-b5bc-246ac87f0435)

**Comment by linchangyi1** [comment]
Hi, thanks for your interest in 9DTact. I have also open source the PCB source file in https://github.com/linchangyi1/9DTact/tree/640c35e9b5cf870f2d5c2a9d42e26e03bbcbaead/9DTact_Design/LED_PCB

Could you please check the files and see whether more information is still needed.

**Comment by abtabrizi** [comment]
> Could you please check the files and see whether more information is still needed.

I did check the files and the manufacturing specs are missing. 
Can you kindly provide a PDF containing the specs listed above? They are necessary for placing PCB orders on JLCPBC. 

Also, for the LEDs, the supplier part # should be updated to C2833055 in the BOM: 
![image](https://github.com/user-attachments/assets/76e068bb-7100-4882-9df3-594a6634fdb7)
