### ISSUE TITLE
Body Collision in SW Model

### ISSUE THREAD

**Issue by abtabrizi** [linchangyi1/9DTact#3]
Hi @linchangyi1, 
I was looking at the `1_Perception_Module.SLDASM` model provided an noticed that a chip on the `led_board.SLDPRT` (Part # CN5711) and the sensor base are colliding:

<img width="1043" alt="error_sensor_base_SW" src="https://github.com/user-attachments/assets/e8f7c1a5-a5b1-4395-acf4-ad0f0d6874a0">
<img width="652" alt="error_sensor_base_SW_2" src="https://github.com/user-attachments/assets/0dd35df9-4cad-45e9-8fb8-a94c47f20726">

Is this just an error in the SW model? 
Please clarify.

**Comment by linchangyi1** [comment]
Hi @abtabrizi, I checked the real board and it should be fine if you have fabricated the PCB:
![IMG_7524](https://github.com/user-attachments/assets/5bed2576-f54b-4a1f-aa8e-1c3deae08400)

Even though, I have placed the chip closer to the center, and it now looks like this:
![105038](https://github.com/user-attachments/assets/e841ae2c-3c66-4a4e-b33e-0f904900e97a)

**Comment by abtabrizi** [comment]
hi @linchangyi1, in the updated LED models the thickness of the board has changed to `1.6 mm`. Previously it was `0.8 mm`. Please clarify what is the actual thickness of the PCB.

**Comment by linchangyi1** [comment]
The JLC software can only export PCB model with the thickness of 1.6mm. While for fabrication, please choose 0.8mm. In addition, I will update the LED model to be 0.8mm thick in solidworks with some tricks.
