### ISSUE TITLE
Regarding Dimension of Molds

### ISSUE THREAD

**Issue by abtabrizi** [linchangyi1/9DTact#4]
hi @linchangyi1, 

I noticed that the inner frame size of the molds are identical. Please refer to the following files on the repo:
**First Mold**: `mold_1.SLDPRT`
**Second Mold:** `mold_2.SLDPRT`

Assuming that the **First Mold is used for the translucent gel**, and the **Second Mold for the Black gel**, the inner frame sizes cannot be identical because the four sides of the translucent gel layer will not get covered by black gel. For your reference I have attached snapshots of the dimensions. 

**Fig. 1** SW model of First Mold
<img width="768" alt="mold_1_dwg" src="https://github.com/user-attachments/assets/ef184292-a00e-40f1-bd39-cd64374c7fd5">

**Fig. 2** SW model of `translucent_gel.SLDPRT`
<img width="617" alt="translucent_gel_dwg" src="https://github.com/user-attachments/assets/73fcaa97-f7be-4fbb-9a99-e21bcf0a59a6">

**Fig. 3** SW model of Second Mold
<img width="781" alt="mold_2_dwg" src="https://github.com/user-attachments/assets/87bf8c7d-084f-42b6-8259-47c19176be0f">

**Fig. 4** SW model of `black_gel.SLDPRT`
<img width="746" alt="black_gel_dwg" src="https://github.com/user-attachments/assets/1fecc172-db6e-4fc9-a84e-c675593837ad">

**Comment by linchangyi1** [comment]
Hi @abtabrizi, thanks a lot for reporting the bug. I just checked the solidworks files and found that I forgot to suppress the cutting feature for mold_2. I have modified it and uploaded the DXF files in the "fabrication" directory.

**Comment by abtabrizi** [comment]
@linchangyi1 Can you please upload the DXF file for the acrylic mold removal tool?

**Comment by linchangyi1** [comment]
I didn't find it on my new computer. You can just use any board that is a bit smaller than the inner size of mold_1.
