### ISSUE TITLE
Are there any pretrained models available?

### ISSUE THREAD

**Issue by JamesHoi** [linchangyi1/9DTact#5]
I noticed that there don't seem to be any pretrained models provided on [https://linchangyi1.github.io/9DTact/](https://linchangyi1.github.io/9DTact/) or [https://github.com/linchangyi1/9DTact](https://github.com/linchangyi1/9DTact). 

Could you please let me know if there are any pretrained models available?

**Comment by linchangyi1** [comment]
I also uploaded it to the folder "saved_models".
