### ISSUE TITLE
Thickness Tolerance of Acrylics 

### ISSUE THREAD

**Issue by abtabrizi** [linchangyi1/9DTact#6]
Hi @linchangyi1, 

I am interested to know the actual measurement for the thickness of the acrylic molds. 
Are the 2.5mm and 2.8mm numbers reported exact measurements or there is a tolerance associated with them (i.e. 2.5 is actually 2.3 when measured with a caliper)?

**Comment by linchangyi1** [comment]
Hi @abtabrizi,

The thickness reported in the paper is an ideal value. Small variations in thickness are acceptable, as long as mold_2 remains thicker than mold_1. However, if the manufactured mold's thickness significantly deviates from the CAD model, you may need to adjust the height of the calibration part according to the new thickness.

**Comment by abtabrizi** [comment]
That makes sense. Does slight variations in the thickness with respect to their ideal values (i.e. 0.3mm difference) impact the results when using your pre-trained model?

**Comment by linchangyi1** [comment]
Yes, that would likely degrade performance. Although the gel layers of your sensor have been ideally manufactured, it's difficult to guarantee good performances if you directly use the open-sourced model to predict the force, because there are various factors that would cause the new sensor's tactile images to differ from the one used for collecting data. Therefore, it's recommended to use the open-source model as pre-trained weights, and collect data from your own sensor to fine-tune the model for better results.

**Comment by abtabrizi** [comment]
Ideally how many images should be collected for fine-tuning the model using the pre-trained weights?

**Comment by linchangyi1** [comment]
No sure about this as I have never tried.

**Comment by abtabrizi** [comment]
Hi, onto another topic, I was wondering what gauge needle (light blue color) was being used in minute 3 of the tutorial (gluing acrylic window to nylon shell)? 
I tried it with 25 gauge needle but it was very difficult to sneak in the glue between the acrylic and the nylon wall, there is hardly any gap. The glue would just spill out onto the surface of the window and the sensor shell.

**Comment by linchangyi1** [comment]
I used 23 gauge needles. This step is almost the most difficult part of the entire process. You need to be very careful in controlling the amount of glue injected.

**Comment by abtabrizi** [comment]
That makes sense. I noticed strange artifacts/particles inside the material of the acrylic window (shown in the images below). There is no dust on the surface of the window because I used the blue stickers to remove dust. The particles become visually apparent when you hold the window under light. Did you notice something like this? Will this be problematic? (I have windows from 2 different manufacturers and both are like this).

![20240826_133651](https://github.com/user-attachments/assets/77c6944a-2c92-4161-9d5d-38223510b918)
![20240916_155010](https://github.com/user-attachments/assets/841e549f-99e9-4674-a380-5a70d7b94c55)

**Comment by linchangyi1** [comment]
I suppose that it's scratch on the surface instead of particles inside the material. I also met this problem and I asked the manufacturer not to remove the film covered on the acrylic board when they cut it. This must be issued for good sensing of the camera.

**Comment by abtabrizi** [comment]
The film stayed on during laser cutting. Does it matter if the thickness of the window is 0.5mm off the ideal value? The reason I'm asking is because I was able to find windows that had less surface imperfections but the thickness is around 1.5mm.

**Comment by linchangyi1** [comment]
If the film stayed during cutting, it should be almost transparent after you take it off. It should be ok to have that thickness as long as you glue it very well.
