### ISSUE TITLE
Manufacturing Black Gel Layer

### ISSUE THREAD

**Issue by abtabrizi** [linchangyi1/9DTact#8]
hi @linchangyi1, when manufacturing the black gel layer, do I fill up the entire space between the mold and the translucent gel with black gel? by the 'space' I'm referring to the 4 sides highlighted below. The spaces are 0.8 and 0.95mm thick. 

![9DTact_Without_Black_Gel](https://github.com/user-attachments/assets/99132404-808b-4d0f-a908-86907c5f5529)
<img width="446" alt="image" src="https://github.com/user-attachments/assets/5fd04d41-1b99-4408-b6ba-ad916628b9ef">
<img width="758" alt="image" src="https://github.com/user-attachments/assets/654a43a5-2d16-4137-a69c-2bbe346b4d2d">

**Comment by linchangyi1** [comment]
Yes, you need to fill it.
